// 获取url地址的类别
var test = window.location.href;
var url = test.split('/');
var value = url[4];
// 判断跳转页面是专享vip还是付费教学还是其他
var titles = $('#pagetitlenode').val();
// 跳转指定页面
function goPage(c){
    // 当前页数
    var page = $('.current').eq(1).text();
    // 总页数
    var a = $('.page-numbers').length-2;
    var pages =$('.page-numbers').eq(a).text();
    if(page == c){
        return;
    }else{
        if(c == pages){
            $('.page-numbers').removeClass('current').eq(a).addClass('current');
        }else{
            $('.page-numbers').removeClass('current').eq(c-1).addClass('current');
        }
        $('.commentlists').empty();
        $('.comments-loading').css('display','block');
        $.ajax({
            type:"GET",
            url: '/content/'+value+'/index_10_'+c+'.json',
            data:{},
            dataType:'json',
            success:function (data) {
                $('.comments-loading').css('display','none');
                var commentList =data.newsList.map(function(list){
                    if(titles == "付费曲谱教学"){
                        if(list.documentDataMap == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                        }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                        }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }else if(list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.productSmallImage == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }else if(list.documentDataMap.productSmallImage == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }else if(list.documentDataMap.readCount == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')            
                        }else if(list.documentDataMap.commentCount == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                 
                        }else{
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }
                    }else if(titles == "vip专区"){
                        if(list.documentDataMap == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                        }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                        }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }else if(list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.productSmallImage == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }else if(list.documentDataMap.productSmallImage == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }else if(list.documentDataMap.readCount == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')            
                        }else if(list.documentDataMap.commentCount == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                 
                        }else{
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }
                    }else{
                        if(list.documentDataMap == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                        }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                        }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }else if(list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.productSmallImage == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }else if(list.documentDataMap.productSmallImage == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }else if(list.documentDataMap.readCount == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')            
                        }else if(list.documentDataMap.commentCount == undefined){
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                 
                        }else{
                            return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                        }
                    }
                })
                $('.commentlists').append(commentList);
            }
        })
    }
}


// 下一页跳转    
// 总页数
var a = $('.page-numbers').length-2;
var pages =$('.page-numbers').eq(a).text();
var i = 1;
var testIndex;
// 大于3页的时候的初始值
var startIndex = 3;
function nextPage(){
    // 判断此时的i是否大于3
    testIndex = i;
    // 当前页数
    var page = parseFloat($('.current').eq(1).text());
    i = page;
    if(i < pages || isNaN(i) && testIndex < pages){
                if(testIndex >= 4){
                    if(i <= 3){
                        $('.page-numbers').removeClass('current').eq(i).addClass('current');
                        testIndex = i +1;
                        i = testIndex;
                    }else{
                        $('.page-numbers').removeClass('current');
                        testIndex++;
                        i = testIndex;
                    }
                }else if(i>=3){
                     $('.page-numbers').removeClass('current');
                     i++;
                }else{
                    $('.page-numbers').removeClass('current').eq(i).addClass('current');
                    i++;
                }
                if(testIndex == pages ){
                    $('.page-numbers').removeClass('current').eq(3).addClass('current');  
                }
                $('.commentlists').empty();
                $('.comments-loading').css('display','block');
                $.ajax({
                    type:"GET",
                    url: '/content/'+value+'/index_10_'+i+'.json',
                    data:{},
                    dataType:'json',
                    success:function (data) {
                        $('.comments-loading').css('display','none');
                        var commentList =data.newsList.map(function(list){
                            if(titles == "付费曲谱教学"){
                                if(list.documentDataMap == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                                }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                                }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }else if(list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.productSmallImage == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }else if(list.documentDataMap.productSmallImage == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }else if(list.documentDataMap.readCount == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')            
                                }else if(list.documentDataMap.commentCount == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                 
                                }else{
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方vip</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }
                            }else if(titles == "vip专区"){
                                if(list.documentDataMap == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                                }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                                }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }else if(list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.productSmallImage == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }else if(list.documentDataMap.productSmallImage == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }else if(list.documentDataMap.readCount == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')            
                                }else if(list.documentDataMap.commentCount == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                 
                                }else{
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">vip专区</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }
                            }else{
                                if(list.documentDataMap == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                                }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                                }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }else if(list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.productSmallImage == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }else if(list.documentDataMap.productSmallImage == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/touxiang.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }else if(list.documentDataMap.readCount == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')            
                                }else if(list.documentDataMap.commentCount == undefined){
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                 
                                }else{
                                    return ('<li class="video-thumb" style="width:24%;clear:none;height:225px;"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p class="gfjx" style="margin-top:10px;">官方教学</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/collectLove.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.favoriteCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                                }
                            }
                         })
                        $('.commentlists').append(commentList);
                    }
                })
    }else{
            if(pages == 1){
                $('.page-numbers').removeClass('current').eq(0).addClass('current');
            }else if(pages == 2){
                $('.page-numbers').removeClass('current').eq(1).addClass('current');
            }else if( pages == 3){
                $('.page-numbers').removeClass('current').eq(2).addClass('current');
            }else{
                $('.page-numbers').removeClass('current').eq(3).addClass('current');
            }
            alert('已经是最后一页了');
    } 
}   