
                 // 获取url地址的类别
var test = window.location.href;
var url = test.substring(33);
var urlName = url.indexOf('/');
var value = url.substring(0,urlName);
// 跳转指定页面
function goPage(c){
    // 当前页数
    var page = $('.current').eq(1).text();
    // 总页数
    var a = $('.page-numbers').length-2;
    var pages =$('.page-numbers').eq(a).text();
    if(page == c){
        return;
    }else{
        if(c == pages){
            $('.page-numbers').removeClass('current').eq(4).addClass('current');
        }else{
            $('.page-numbers').removeClass('current').eq(c-1).addClass('current');
        }
        $('.commentlists').empty();
        $('.comments-loading').css('display','block');
        $.ajax({
            type:"GET",
            url: '/content/friend/'+value+'/index_20_'+c+'.json',
            data:{},
            dataType:'json',
            success:function (data) {
                $('.comments-loading').css('display','none');
                var commentList =data.newsList.map(function(list){
                    if(list.documentDataMap == undefined){
                        return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/LOGO.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                    }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                        return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/LOGO.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                    }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined){
                        return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                    }else if(list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                        return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/LOGO.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                    }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.productSmallImage == undefined){
                        return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/LOGO.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                    }else if(list.documentDataMap.productSmallImage == undefined){
                        return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/LOGO.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                    }else if(list.documentDataMap.readCount == undefined){
                        return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')            
                    }else if(list.documentDataMap.commentCount == undefined){
                        return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                 
                    }else{
                        return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                    }
                })
                $('.commentlists').append(commentList);
            }
        })
    }
}


// 下一页跳转    
// 总页数
var a = $('.page-numbers').length-2;
var pages =$('.page-numbers').eq(a).text();
// 当前页数
var page = parseFloat($('.current').eq(2).text());
var i = page;
function nextPage(){
    if(i < pages){
                if(i>3){
                     i++;
                }else{
                    $('.page-numbers').removeClass('current').eq(i).addClass('current');
                    i++;
                }
                $('.commentlists').empty();
                $('.comments-loading').css('display','block');
                $.ajax({
                    type:"GET",
                    url: '/content/friend/'+value+'/index_20_'+i+'.json',
                    data:{},
                    dataType:'json',
                    success:function (data) {
                        $('.comments-loading').css('display','none');
                        var commentList =data.newsList.map(function(list){
                            if(list.documentDataMap == undefined){
                                return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/LOGO.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                            }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                                return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/LOGO.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')            
                            }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.commentCount == undefined){
                                return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../themebasic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                            }else if(list.documentDataMap.commentCount == undefined && list.documentDataMap.productSmallImage == undefined){
                                return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/LOGO.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                  
                            }else if(list.documentDataMap.readCount == undefined && list.documentDataMap.productSmallImage == undefined){
                                return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/LOGO.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                            }else if(list.documentDataMap.productSmallImage == undefined){
                                return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="../../../theme/basic/images/LOGO.png" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                            }else if(list.documentDataMap.readCount == undefined){
                                return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">0</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')            
                            }else if(list.documentDataMap.commentCount == undefined){
                                return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">0</a></span></p></div><div class="clear"></div></article></li>')                                 
                            }else{
                                return ('<li class="video-thumb"><article><a class="pic" target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark"><img class="lazy" src="/file/'+list.documentDataMap.productSmallImage.dataValue+'" alt="#" style="width: 100%;height: 125px;" /></a><div class="video-info"><h2><a target="_blank" href="'+list.viewUrl+'" title="链接到  '+list.title+'" rel="bookmark">'+list.title+'</a></h2><p>琴友：<a target="_blank" href="#" title="">'+list.author+'</a></p><p>'+list.publishTime+'</p><p class="post-meta"><span><img src="../../../theme/basic/images/video.png" alt="" style="width:11px;height: 11px;padding-right: 5px;">'+list.documentDataMap.readCount.dataValue+'</span><span><img src="../../../theme/basic/images/zan.png" alt="" style="width: 14px;height:14px;padding-right: 5px;">'+list.documentDataMap.praiseCount.dataValue+'</span><span><img src="../../../theme/basic/images/pao.png" alt="" style="width:11px;height: 11px;padding-right: 5px;"><a href="#">'+list.documentDataMap.commentCount.dataValue+'</a></span></p></div><div class="clear"></div></article></li>')                                  
                            }
                        })
                        $('.commentlists').append(commentList);
                    }
                })
    }else{
            if(pages == 1){
                $('.page-numbers').removeClass('current').eq(0).addClass('current');
            }else if(pages == 2){
                $('.page-numbers').removeClass('current').eq(1).addClass('current');
            }else if( pages == 3){
                $('.page-numbers').removeClass('current').eq(2).addClass('current');
            }else{
                $('.page-numbers').removeClass('current').eq(4).addClass('current');
            }
            alert('已经是最后一页了');
    } 
}   