var html='';
html+='<nav class="navbar navbar-inverse navbar-fixed-top">';
html+='      <div class="container-fluid">';
html+='        <div class="navbar-header">';
html+='         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">';
html+='           <span class="sr-only">Toggle navigation</span>';
html+='            <span class="icon-bar"></span>';
html+='            <span class="icon-bar"></span>';
html+='            <span class="icon-bar"></span>';
html+='          </button>';
html+='          <a class="navbar-brand" href="#">${systemName}管理中心</a>';
html+='        </div>';
html+='        <div id="navbar" class="navbar-collapse collapse">';
         
html+='		<ul class="nav navbar-nav navbar-right hidden-xs">';
html+='           <li><a href="/config.shtml" target="_blank">设置</a></li>';
html+='            <li><a href="/user/logout.shtml">退出</a></li>';
html+='            <li><a href="#">关于</a></li>';
html+='          </ul>';
html+='          <div class="navbar-right hidden-xs" style="color:#9d9d9d;height:50px;line-height:50px;">';
html+='			欢迎您，${welcomeName}！';
html+='          </div>';
html+='		   <ul class="nav navbar-nav navbar-right operate" id="operate">';
html+='			<li><a id="text" href="#">文本</a></li>';
html+='			<li><a id="bgd" href="#">背景</a></li>';
html+='			<li><a id="music" href="#">音乐</a></li>';
html+='			<li><a id="video" href="#">视频</a></li>';
html+='			<li><a id ="picture" href="#">图片</a></li>';
html+='			<li><a id="input" href="#">输入框</a></li>';
html+='			<li><a id="button" href="#">按钮</a></li>';
html+='			<li><a id="pics" href="#">图集</a></li>';
html+='		</ul>	';
html+='		<ul class="nav navbar-nav navbar-right operate setting" >';
html+='            <li><a href="/config.shtml" target="_blank">设置</a></li>';
html+='            <li><a href="/user/logout.shtml">退出</a></li>';
html+='            <li><a href="#">关于</a></li>';
html+='          </ul>';
html+='        </div>';
html+='      </div>';
html+='    </nav>';
$(html).insertAfter("body");